import psycopg2
import postgresql_util
import sqlalchemy_util
import records_util
import records
import env

connection = psycopg2.connect(**env.postgresql)
connection.autocommit = True
cursor = connection.cursor()
cursor.execute('delete from t')
cursor.execute('insert into t values (1,2)', None)
cursor.executemany('insert into t values (010,020)', [1, 2])
cursor.execute('select %(a)s from dual', {'a': '2'})
# cursor.execute('select %(a)s from dual', a='3')
# data = cursor.fetchone()
# data = cursor.fetchmany(8)
cursor.execute('select * from t')
data = cursor.fetchall()
print(data)
cursor.close()
connection.commit()
connection.close()

database = postgresql_util.SqlUtil(**env.postgresql)
# print(database.query('insert into t values (1,2)', fetchall=False))
print(database.query('insert into t values (%s,%s)', ('3', 4), fetchall=False))
print(database.save_data((5, 6), 't'))
print(database.query('select %(a)s from dual', {'a': '2'}, keep_args_as_dict=True))
print(database.query('select 1 from dual'))
print(database.query('select * from t'))

connection = records.Database('postgresql://{user}:{password}@{host}:{port}/{database}'.format(
    **env.postgresql)).get_connection()
connection.bulk_query('insert into t values (7,8)')
connection.bulk_query('insert into t values (:a,:b)', {'a': 9, 'b': 10})
connection.bulk_query('insert into t values (:a,:b)', ({'a': 11, 'b': 12},))
connection.bulk_query('insert into t values (:1,:2)', [{'1': 13, '2': 14}])
print(connection.query('insert into t values (15,16)').all())
print(connection.query('insert into t values (:a,:b)', **{'a': 19, 'b': 20}).all())
print(connection.query('insert into t values (:1,:2)', **{'1': 17, '2': 28}).all())
print(connection.query('select :a from dual', **{'a': '2'}).all())
print(connection.query('select :a from dual', a='3').all())
print(connection.query('select 1 from dual').all())
print(connection.query('select * from t').all())
print(connection.query('select 1 from dual').dataset)
print(connection.query('select * from t').dataset)

database = records_util.SqlUtil(dialect='postgresql', **env.postgresql)
# print(database.query('insert into t values (1,2)', fetchall=False))
print(database.query('insert into t values (:a,:b)', {'a': '23', 'b': '24'}, keep_args_as_dict=True, fetchall=False))
print(database.save_data(('21', '22'), 't'))
print(database.query('select :a from dual', {'a': '2'}, keep_args_as_dict=True, origin_result=True))
print(database.query('select 1 from dual', origin_result=True))
print(database.query('select * from t', origin_result=True))
print(database.__dict__)
print(database.connection._conn.get_isolation_level())
database.autocommit = False
print(database.query('insert into t values (100,200)', fetchall=False))
print(database.query('select * from t', origin_result=True))
database.try_connect()
print(database.query('select * from t', origin_result=True))
database = records_util.SqlUtil(dialect='postgresql', autocommit=False, **env.postgresql)
print(database.query('select * from t', origin_result=True))
print(database.query('insert into t values (300,400)', fetchall=False))
print(database.query('select * from t', origin_result=True))
database.try_connect()
print(database.query('select * from t', origin_result=True))

database = sqlalchemy_util.SqlUtil(dialect='postgresql', **env.postgresql)
# print(database.query('insert into t values (1,2)', fetchall=False))
print(database.query('insert into t values (:a,:b)', {'a': '23', 'b': '24'}, keep_args_as_dict=True, fetchall=False))
print(database.save_data(('21', '22'), 't'))
print(database.query('select :a from dual', {'a': '2'}, keep_args_as_dict=True, origin_result=True))
print(database.query('select 1 from dual', origin_result=True))
print(database.query('select * from t', origin_result=True))
print(database.__dict__)
print(database.connection.get_isolation_level())
database.autocommit = False
print(database.query('insert into t values (500,600)', fetchall=False))
print(database.query('select * from t', origin_result=True))
database.try_connect()
print(database.query('select * from t', origin_result=True))
database = sqlalchemy_util.SqlUtil(dialect='postgresql', autocommit=False, **env.postgresql)
print(database.query('select * from t', origin_result=True))
print(database.query('insert into t values (700,800)', fetchall=False))
print(database.query('select * from t', origin_result=True))
database.try_connect()
print(database.query('select * from t', origin_result=True))
